language: node_js
node_js:
  - "6"
cache:
  directories:
  - node_modules # NPM packages
before_install:
  - npm install
  - node run build
env:
  - COMMAND=lint
  - COMMAND=test
script:
  - npm run "$COMMAND"
notifications:
  email:
    on_failure: change
    on_success: change
